### ISSUE TITLE
Generate static website parts using Hugo

### ISSUE THREAD

**Issue by heinrichreimer** [uhh-lt/cam#101]
Besides the actual search on Elasticsearch, the CAM website is basically static.
We could encorporate that in the frontend architecture.
With the [Hugo](https://gohugo.io/) static page generator, we might be able to improve the website's speed.

At a first glance the following components are static (or could be implemented static):
- [about](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/about)
- [api-info](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/api-info)
- [contact](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/contact)
- [header](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/header)

The following aren't:
- [keyword-search](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/keyword-search)
- [result-presentation](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/result-presentation)
- [context-presentation](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/shared-components/context-presentation)
- [user-interface](https://github.com/uhh-lt/cam/tree/master/src/Frontend/camFrontend/src/app/components/user-interface)

I know, moving to a more "static" approach is opinionated, that's why I would love to hear your thoughts.

**Comment by alexanderpanchenko** [comment]
I find that though what may be useful is actually to enable the possibility to EDIT some static parts more easily i.e. using Markdown and not editing any source codes. This may be the reason to introduce Hugo. However, I do not understand what this would technically mean: which steps you need to do to deploy a web site using Hugo? Which software need to be installed (I guess the Hugo compiler at least)?
