### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by heinrichreimer** [uhh-lt/cam#103]
To simplify documenting and using the API, we could switch to GraphQL: https://graphql.org/

There are already frameworks and plugins to integrate it with Python: https://graphql.org/code/#python

One major benefit is that we could separate the API specification from both, frontend and backend code. Also the GraphQL could be mocked for testing. And finally, GraphQL supports [field deprecation](http://spec.graphql.org/June2018/#sec-Field-Deprecation), which is useful for fast-paced API development.

**Comment by heinrichreimer** [comment]
In my previous experience, using the GraphQL schema as the single source of truth for the API has greatly improved the ability to work in multiple teams on different parts of the code base.

**Comment by alexanderpanchenko** [comment]
The thing is that we currently do not have multiple teams working on the same codebase. See my previous email related to this issue.
