### ISSUE TITLE
Additional information for Requirements installation for backend

### ISSUE THREAD

**Issue by mozzam4** [uhh-lt/cam#105]
The Requirements mentioned in backend folder cannot be directly installed in Python 3.8 as there are lot of discrepancies. I followed the below steps, which can be considered adding in the Readme file separately for backend. 
1. create a new python environment in python 3.6 : I created in conda
2. Install this set of requirements with PIP - 
[Installed_thru_pip.txt](https://github.com/uhh-lt/cam/files/4372759/Installed_thru_pip.txt)
3. Install the second set through conda 
[installed_with_conda.txt](https://github.com/uhh-lt/cam/files/4372762/installed_with_conda.txt)
4. Install the remaining with Pip by removing the version
[pip_without_version.txt](https://github.com/uhh-lt/cam/files/4372765/pip_without_version.txt)
5. Upgrade numpy to the latest.

The backend should work well after this. 

Best Regards,
Mozzam

**Comment by alexanderpanchenko** [comment]
Thank you very much. Indeed Python 3.8 was simply not there when the system was originally developed.  I've noted these useful notes of your experience. I think it would be however in the future better to migrate / ensure compatibility with the latest version of python so if you can try to migrate to the python 3.8 gradually and make the required changes it would be better than freezing the software to python3.6 version.
