### ISSUE TITLE
Dead link (infersent.allnli.pickle) in Readme

### ISSUE THREAD

**Issue by heinrichreimer** [uhh-lt/cam#106]
The Link in the [Deployment without Docker](https://github.com/webis-de/cam#backend) section to the InferSent model download (https://s3.amazonaws.com/senteval/infersent/infersent.allnli.pickle) is broken.
The URL answers with:
```xml
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>senteval</BucketName>
  <RequestId>9134752924E2ED04</RequestId>
  <HostId>0UJfZmGNEXIFXpllgpGDshma+c1rzFe/VWWSFbAXDm02QL2nCVl8i0OsKHoqdttCWU+qP7ZYySk=</HostId>
</Error>
```
Supposedly, InferSent seems to have updated their pretrained models (see https://github.com/facebookresearch/InferSent/issues/128 and [similar issues](https://github.com/facebookresearch/InferSent/search?q=infersent.allnli.pickle&type=Issues)), and the old one is no longer available

Which of the [new Models](https://github.com/facebookresearch/InferSent/search?q=infersent.allnli.pickle&type=Issues)should we use, or do you have a copy of the `infersent.allnli.pickle` file?

**Comment by alexanderpanchenko** [comment]
https://drive.google.com/file/d/1PW5jKTzwYznIprtEWpJn_zOtexal4e57/view
