### ISSUE TITLE
Stability issue

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#47]
Quite often no results are not returned from the index and the reasons why it happens it is not clean. We need to debug this issue. 

To inform the user about the status it is needed to provide some information about the progress of search: getting X documents form the index, computing the scores, ...

**Comment by mschild** [comment]
Do you have an example pair were this issue happens?

This are some times for the processing of microsoft vs. apple
--- 3.5280957221984863 seconds (request_es)---
--- 0.13251519203186035 seconds (extract_sentences)---
--- 3.3118503093719482 seconds (clear_sentences)---
--- 2.496230125427246 seconds (find_winner)---

**Comment by mschild** [comment]
Maybe the ES or the Backend were down at this moment, if this happens now, a message is shown and the loading is stopped.

**Comment by alexanderpanchenko** [comment]
Actually not: not sure exactly what happened. Sometimes it worked (on my
machine) sometimes didn't. The ltcpu1 was not heavily loaded.
