### ISSUE TITLE
colors of the demo

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#48]
making the colors here (red/green) 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1456830/39126400-90fe7e8c-4702-11e8-824a-95b240f429f6.png">

the same as here
<img width="140" alt="image" src="https://user-images.githubusercontent.com/1456830/39126412-a49905de-4702-11e8-93b6-73e5fd2f508d.png">

**Comment by mschild** [comment]
Will be there on next deploy
