### ISSUE TITLE
Not all sentences get found

### ISSUE THREAD

**Issue by mschild** [uhh-lt/cam#54]
For example: "Yes, CUDA has been around longer, receives more support, and is a better product in almost all ways then OpenCL." doesn't get found.
Is found by _cuda AND opencl AND better AND then_ in Kibana, but not by the backend query!
The query produced by the backend ..._OR ("better then") OR_... probably should be ..._OR (better AND then) OR_...

Should this be changed before the evaluation? The calculated scores might change a lot.

**Comment by alexanderpanchenko** [comment]
better AND then is too generic actually

we need something like "better word{0,5} then". actually
elasticsearch syntax should allow for such queries (but your solution I
would suggest not to use at the moment - we tried it and it seems to
provide less precise results)

**Comment by mschild** [comment]
Ok, I see, maybe later we can try something like: ["better then"~5](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-query-string-query.html#_proximity_searches)

Another thing I'm wondering about:
In the constants \\' is used for multi word markers (e.g.  "_\\'more complicated\\'_") this leads to ..._('more complicated' AND than)_... in the query, which is an implicit OR between "more" and "complicated", if I am not mistaken. 
Is that a wanted behaviour?

**Comment by alexanderpanchenko** [comment]
regarding the second question: check with Kibana console. i think if you do
quotes, it should be an exact match AFAIK

**Comment by alexanderpanchenko** [comment]
overall: do not worry too much about the performance of the current system.
one of the goals will be to integrate the system based on ML (of Mirco),
which is supposed to be much more accurate
