### ISSUE TITLE
It is only searched for words without special characters

### ISSUE THREAD

**Issue by mschild** [uhh-lt/cam#59]
https://github.com/uhh-lt/cam/blob/cac87cc0484437ec7ca484ad58e3ffee00db25e8/src/Backend/sentence_clearer.py#L56

If the compared objects both contain special characters most sentences will be dismissed.
(At the moment it is not possible to compare "iphone 5" with "galaxy s4"

**Comment by alexanderpanchenko** [comment]
yes, that's bad.
