### ISSUE TITLE
Deploy the application with docker

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#61]
Use docker and docker compose to deploy our application: 

- https://www.docker.com/
- https://docs.docker.com/compose/

**Comment by alexanderpanchenko** [comment]
Here is a couple of extra details:

1. The built image should be deployed at Docker Hub currently simply under your own account. 

2. When deploying to ltdocker please follow these rules: 

- put the data into /srv/docker in a subdirectory 
- make sure that docker-compose is in a sub-directory
- make sure that the name of the sub-directory starts from "pan" in this directory, e.g. pancam

**Comment by ChulioZ** [comment]
From my understanding the docker deployment on ltdocker should now be complete. The docker-compose.yml is in the pan-cam subdirectory and the two containers for back end and front end should be up and running (`docker ps` shows them).

There are a few questions remaining though:

1. I don't know how I can test if the containers are actually working correctly. They're working for me locally when I actually visit the pages in my browser but I don't know how I could do that on the server. How could I do that?

2. With `docker ps` I don't see any port forwardings unter PORTS. Some other projects have their forwardings included there but for our two containers I don't see them. Does that mean the forwarding didn't work and I should check my docker-compose.yml or is it just not shown? If so, how can I make them show there?

3. When building the frontend image with docker I get a couple of warnings. They don't seem to end up mattering for the basic functionality, but as warnings are always bad, maybe we can do something about them?

> Step 6/10 : RUN npm install
>  ---> Running in 58d40256c881
> npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
> npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
> npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
> npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
> npm WARN deprecated uws@9.14.0: stop using this version
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated buildmail@4.0.1: This project is unmaintained
> npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> Step 7/10 : RUN npm install -g @angular/cli

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by ChulioZ** [comment]
As requested, I've also cloned the project into another subdirectory.

**Comment by alexanderpanchenko** [comment]
Great, thank you for the update!

1. To test it connect ssh tunnels to the ltdocker and run in your browser the system making sure it works, e.g. ``ssh -L 8888:localhost:8888 ltdocker``

2. Yes, it looks like you need to set the forwarding - look as it is done in other .docker-compose.yml files in the /srv/docker directory 

3. Some nmp related stuff, @mschild can you comment on these warnings, please?

4. You shoud set the name of the container - see the NAMES column of the other containers
 
```
CONTAINER ID        IMAGE                                                     COMMAND                   CREATED             STATUS                  PORTS                                              NAMES
f83cf49a12ca        chulioz/cam:backend                                       "python main.py"          About an hour ago   Up About an hour        5000/tcp                                           cam_backend.1.x950huri090c1djv79iy5vawj
e41b012f4c9e        chulioz/cam:frontend                                      "/bin/sh -c 'ng serv…"    About an hour ago   Up About an hour        4200/tcp                                           cam_frontend.1.nf0eaw5t4vnyodoxw9o9501uf
e70a661a4143        uhhlt/nodweb                                              "/bin/sh -c 'rm -f /…"    17 hours ago        Up 17 hours             0.0.0.0:10008->9000/tcp                            smynodstud_nodweb_1
84cfcda52319        uhhlt/nodcore                                             "/bin/sh -c 'crond -…"    17 hours ago        Up 17 hours                                                                smynodstud_nodcore_1
c212d23d2dad        uhhlt/newscrawler                                         "/bin/sh -c 'crond -…"    17 hours ago        Up 17 hours                                                                smynodstud_crawler_1
ad125c21ea39        elasticsearch:5.5.2-alpine                                "/docker-entrypoint.…"    17 hours ago        Up 17 hours             0.0.0.0:9200->9200/tcp, 9300/tcp                   smynodstud_elasticsearch_1
61929db810d4        kibana:5.5.2                                              "/docker-entrypoint.…"    17 hours ago        Up 17 hours             0.0.0.0:5601->5601/tcp                             smynodstud_kibana_1
cc15e2b7b941        mariadb                                                   "docker-entrypoint.s…"    17 hours ago        Up 17 hours (healthy)   3306/tcp                                           smynodstud_db_1
```

**Comment by mschild** [comment]
Seems to be a known issue on the latest version of cli:
https://github.com/angular/angular-cli/issues/10023
https://github.com/angular/angular-cli/issues/10022

I will start the docker container locally and have a closer look (tomorrow or monday).

**Comment by mschild** [comment]
At least the most warnings should be dismissed with the latest commit.
(not removed: 
- npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
- npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

)
The packages are dependencies of the package "karma", which is a dev depencency, so it is probably not too bad.

**Comment by ChulioZ** [comment]
Deployment should be complete; I've sent you a mail with the details.
