### ISSUE TITLE
Make sure that in the ML models sentences are ranked by confidence of the classifier

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#62]
The sentences should be ranked not randomly - use ``probas = classifier.predict_proba`` function 
to get these or similar. 

![image](https://user-images.githubusercontent.com/1456830/41163112-14489e04-6b38-11e8-94f6-50503a6b75f3.png)

BTW, note that @ChulioZ will take care of #61 (and other eventual tickets with him being assigned to it).

**Comment by mschild** [comment]
commit b80590a7da3944b3bbc35f2a19082874c0923bc8 already implemented this, but I will check it once again

**Comment by mschild** [comment]
Alright, actually the order is reversed... so the sentence with the least confidence is on the top of the result... 
sentences_with_confidence.sort() -> sentences_with_confidence.sort(reverse = True) solves this issue.

@alexanderpanchenko Pretty sad, that this bug also influenced the prestudy, but on the other hand, this probably will be a big performance boost for the main study... 👍

**Comment by alexanderpanchenko** [comment]
Ok!
