### ISSUE TITLE
parallel classification - ml model

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#64]
when sentences are classified multiple cores should be used to make the process faster - if it is not the case now - to speed up the process. 

you can use 'multiprocessing' module to achieve this goal, e.g. using the Pool class with a global shared variable where the model is stored

**Comment by mschild** [comment]
Unfortunately, I think that the use of multiprocessing is of no use, since apparently all cores are already in use:
![grafik](https://user-images.githubusercontent.com/13733275/44322767-46ae4d80-a44f-11e8-84de-1aa281896ecb.png)

**Comment by alexanderpanchenko** [comment]
Ok

**Comment by alexanderpanchenko** [comment]
Ok
