### ISSUE TITLE
public es instance

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#66]
@mschild could you please write if the current version of the system relies on this ES endpoint or not 
https://ltdemos.informatik.uni-hamburg.de/depcc-index/ (reader:reader) 

we can't find it in the code

**Comment by mschild** [comment]
Yes the version is used, on the Server it is piped on localhost:9200

**Comment by alexanderpanchenko** [comment]
And why not to use ltdemos.infrmatik.uni-hamburg.de/depcc-index?

On Jun 14, 2018 6:25 PM, "Matthias Schildwächter" <notifications@github.com>
wrote:

As described in the readme, the main has to be started with "python main.py
reader reader"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uhh-lt/cam/issues/66#issuecomment-397355993>, or mute
the thread

**Comment by mschild** [comment]
You mean directly without pipe? Just convenience, since then it is the same as in local use. I will change that.

**Comment by alexanderpanchenko** [comment]
ok. i think it is better to use one global uri as then no matter where you
deploy the system it will work.

**Comment by mschild** [comment]
Now http://134.100.15.203:9200/ is used on the deployed instance, no more pipe is needed.
I think that is not the global version you mentioned, but the version behind the public accessible Kibana.
I tested the global one (https://ltdemos.informatik.uni-hamburg.de/depcc-index/)  locally, but I get an certificate error.

**Comment by alexanderpanchenko** [comment]
what is the certificate error? I think you just shoud accept the
certificate of UHH or something like this. Please write to Eugen Ruppert in
case you cannot resolve the HTTPS certificate issue - he set it up.

**Comment by mschild** [comment]
The backend should use http://ltdemos.informatik.uni-hamburg.de/depcc-index/ instead of https://...

**Comment by alexanderpanchenko** [comment]
ok, sorry, yes, it can be the issue

**Comment by ChulioZ** [comment]
This should be resolved by now, right? For me it's working without problems.

**Comment by mschild** [comment]
Yes, using http instead of https solves the issue. (solved by fddd27f8415ff9c849d71769abaf1dd60475ad7e)
