### ISSUE TITLE
Can't start the frontend any more due to errors with rxjs

### ISSUE THREAD

**Issue by ChulioZ** [uhh-lt/cam#67]
Hey,

when I tried to start the frontend via `ng serve -o` I get the following error message:

> ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(1,22): error TS2305: Module '"C:/.../GitHub/cam-hci/src/Frontend/camFrontend/node_modules/rxjs/Rx"' has no exported member 'Subscribable'.

I then tried to follow the instructions from [this thread](https://github.com/angular/flex-layout/issues/702). I tried to downgrade to rxjs@5.0.0-beta.14 but I always get the error message 

> npm ERR! notarget No matching version found for rxjs@5.0.0-beta14

I then tried the other suggestion and installed `npm i rxjs@forward-compat --save` but I then get the warnings the user in the other thread also described:

> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 1052:55-71 "export 'defineInjectable' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 289:43-49 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 290:47-53 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 291:46-52 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3028:140-146 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3028:168-174 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3028:54-70 "export 'defineInjectable' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3379:134-140 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3379:166-172 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3379:197-203 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3379:218-224 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 3379:52-68 "export 'defineInjectable' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 433:158-164 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 433:60-76 "export 'defineInjectable' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 664:134-140 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 664:150-156 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 664:171-177 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 664:52-68 "export 'defineInjectable' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 936:140-146 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 936:168-174 "export 'inject' was not found in '@angular/core'
> 
> WARNING in ./node_modules/@angular/flex-layout/esm5/core.es5.js
> 936:54-70 "export 'defineInjectable' was not found in '@angular/core'
> 
> webpack: Compiled with warnings. 

Although it says Compiled with warnings, I don't actually get to see anything in the browser, just a blank page.

So what should I do here?

**Comment by mschild** [comment]
How do you install the frontend dependencies?
Seems to be, that the latest version (6+) is installed, but 5.2 or something is needed.
I think, the easiest way is to migrate the frontend to the latest, I will do that tomorrow.
I will notify you when I'm done and then you could try again to set it up

**Comment by mschild** [comment]
You now could try again to start the service.

**Comment by ChulioZ** [comment]
It's working now, thanks for migrating!
