### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#68]
can you please take a look - currently the backend seems to be down

**Comment by mschild** [comment]
I am not at home at the moment, I will have a look tomorrow morning.

**Comment by alexanderpanchenko** [comment]
Ok. No problem.

**Comment by mschild** [comment]
Pipe was shut down, now not needed anymore.
(Solved by 31f6b444d6de90e04931915619bda99c113a1839)
