### ISSUE TITLE
Travis test fails due to log length

### ISSUE THREAD

**Issue by mschild** [uhh-lt/cam#69]
Quite annoying, is it possible to make the log length bigger?

**Comment by alexanderpanchenko** [comment]
Not sure what do you mean? Which log? Yes, it should be no problem to do it.

**Comment by mschild** [comment]
_The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over)._
That message seems to be the reason for terminating the travis job. It appears while downloading torch (which is about 500mb big)

It appears e.g. on https://travis-ci.org/uhh-lt/cam/jobs/393540665#L448 if you wait about 10 seconds.

**Comment by alexanderpanchenko** [comment]
Why do you need torch? Is it to use xgboost?

**Comment by mschild** [comment]
I don't really know, should be something used by Mirco's model, without it the models won't work.
It could be a possibility to split up the dependency files in two, one for the basic setup (all what is needed for the unit tests) and one for ML parts.

**Comment by alexanderpanchenko** [comment]
please try to figure it out: it is important to know.

i would be really good to know why torch is needed (it is normally not used
as far as i know) - maybe we can substitute it by something lighter

**Comment by alexanderpanchenko** [comment]
i checked the code - i understood why it is needed.

i think we cannot easily avoid using it, BUT still it is not clear why
tests fail (while downloading 500mb can take a while it should still work)

**Comment by alexanderpanchenko** [comment]
try usint travis_wait

https://docs.travis-ci.com/user/common-build-problems/

**Comment by mschild** [comment]
I will try that, when Julian resolved the issues I commented on his commits. 
Maybe it could make sense to work with branches now?

**Comment by ChulioZ** [comment]
They should be resolved by now.

**Comment by mschild** [comment]
Expanding the _pip install_ command with _--quiet_ resolved the issue of exceeding the log length (from 8aa9495dc49af0f6697a5782b6cedcb8a41b0ada it is working now)

**Comment by alexanderpanchenko** [comment]
I agree - branches would make sense a lot. Just make sure they are 'feature
branches' with an isolated updates related to a certain feature to avoid
large merge conflicts later.
