### ISSUE TITLE
new user study experiment

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#70]
In the final version of the experiments for the MA thesis, we need to replicate the pre-study at the larger scale, taking into account limitations of the pre-study. 

One improvement in the design we discussed today is a split into three categories: keyword search, cam, and voice interface, which emulates a real human. For this, we would need to gather answers to a comparative question from a platform, like Quora (like this one https://www.quora.com/How-do-Scala-programming-language-and-Ruby-Python-compare-for-writing-web-apps) and then vocalize them, presenting to the user. 

The expectation is that the cam will be faster, but also more accurate to answer the questions, but of course it is a matter of the experiment to test it.

**Comment by mschild** [comment]
So basically, the keyword search again is Kibana, cam is the updated final version of our system and the voice interface is a mocked interface, which just outputs gathered answers from Quora?

**Comment by alexanderpanchenko** [comment]
Yes. Kind of - the first two types of hci aren't changed here.
