### ISSUE TITLE
show sentences containing the aspect

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#72]
Aspects can be of great use for retrieval of information, but now it is difficult to navigate though them:
![image](https://user-images.githubusercontent.com/1456830/42275369-bc56e3fc-7f98-11e8-89a3-88e79abc2895.png)

They are just presented in a form of a list. Some of them are irrelevant (subject to further improvement) making real use of them very small. 

We need to make each automatically extracted aspect clickable. Once clicked only those sentences which contain the aspect should remain. A user should be able to select several aspects at the same time as well or remove already selected filter by an aspect (aspects).

**Comment by mschild** [comment]
On the actual feature branch I investigated a similar functionality. When such generated aspect is clicked, it is added to the list of entered aspects and also taken into accout when the comparison is started again.

**Comment by alexanderpanchenko** [comment]
this is not exactly the same, but is still useful

i speak about the scenario, where you just filter our bunch of sentences shown to the user

**Comment by alexanderpanchenko** [comment]
- yes. this is exactly what I mean. 
- yes: selecting more than one aspect should be possible.
- the mockup looks good, besides
- I like this UI element: actually, this is something I also thought about (the current list presentation is terribly wasteful in terms of space)

![image](https://user-images.githubusercontent.com/1456830/42289986-60091920-7fcb-11e8-8382-a637704827df.png)

**Comment by alexanderpanchenko** [comment]
a small update: i belive however, that this UI element is kind of overkill: 

![image](https://user-images.githubusercontent.com/1456830/42290030-9322119a-7fcb-11e8-9cd9-fae6928ae066.png)

instead, I think that this element should be just clickable (work as a filter). a clicked button should change the color or something like this: 

![image](https://user-images.githubusercontent.com/1456830/42290047-b14f8d32-7fcb-11e8-9eb0-a5d02a6a9789.png)

**Comment by mschild** [comment]
Actually it is fully functional, the score presentation looks like this for the same example:
![grafik](https://user-images.githubusercontent.com/13733275/42305930-65fd811a-802d-11e8-871c-d7728d1694ee.png)

So the filter functionality would be on top of the entered aspects or do we want to query only general sentences and afterwards filter with the generated aspect buttons?

**Comment by alexanderpanchenko** [comment]
if it is already functioning I suggest already deploying it, e.g. here http://ltdemos.informatik.uni-hamburg.de/cam2

This way the new version will be already functioning, and we can try various options. 

However, I also suggest another deployment, like http://ltdemos.informatik.uni-hamburg.de/cam3, which would contain no opening sections with sentences:

![image](https://user-images.githubusercontent.com/1456830/42316510-b25f5a86-8052-11e8-9096-6ca5e2b00e64.png)
 

I also have a question: this UI element displays only user-entered aspects?

![image](https://user-images.githubusercontent.com/1456830/42316525-c03f0642-8052-11e8-9d6d-119371f98fda.png)

**Comment by mschild** [comment]
Yes, good idea, i will deploy it.

No opening sections would mean directly showing the sentences (sorted) and with the filtering option?

Yes, diameter and mass are the entered aspects, there only the sentences containing only the one aspect are considered.
General Comparison: Are those sentences containing none of the entered aspects. 
Multiple Aspects: Sentences containing more than one aspect.
Overall: All scores of the sentences combined

**Comment by alexanderpanchenko** [comment]
> Yes, good idea, i will deploy it.

ok. great! ask Eugen if a change in the Apache proxy is needed

> No opening sections would mean directly showing the sentences (sorted) and with the filtering option?

yes

**Comment by mschild** [comment]
As soon as Eugen answers my mail I will deploy the two new versions as well.

I introduced your idea in another branch (a802a10423978b36eefbe99d93fb391d47e53fff) also kind of nice, maybe a combination would also be great. I let you know if I deployed it (I hope tomorrow)
![grafik](https://user-images.githubusercontent.com/13733275/42338379-f17d601e-8089-11e8-8e6d-82f8b3236fe6.png)

**Comment by alexanderpanchenko** [comment]
great.

about the combination - in ui design a minimalism is a king. sometimes we
need to make hard decisions to cut functionality so i would like to test
both and select one which fits the best

**Comment by mschild** [comment]
You can find the filter feature [here](http://ltdemos.informatik.uni-hamburg.de/cam2/cam2#/) and the version with the splitted scores [here]( http://ltdemos.informatik.uni-hamburg.de/cam3/cam3#/).
The Infersent model is not working at the moment, because the model has to be placed in the Docker container.

**Comment by mschild** [comment]
1d582226dced25ec04f06c4f2f4792ddfbcd9bfb merged the both branches together and kept the discussed features (master now holds the splitted scores presented by charts and a filter option for aspects)
