### ISSUE TITLE
we have some duplicates unfiltered

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#75]
![image](https://user-images.githubusercontent.com/1456830/42633580-3d05c4ac-85e1-11e8-9572-0d729ff376b0.png)

**Comment by ChulioZ** [comment]
They're not really duplicates -- if you look closely you'll see that the sentences are in fact different with different types of cars in this case. Do you still want them filtered?

**Comment by alexanderpanchenko** [comment]
Yes, you are right. Let's close it for now.
