### ISSUE TITLE
put the reset button on the left of the 'compare' button

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#78]
![image](https://user-images.githubusercontent.com/1456830/42635659-e8ad1af8-85e6-11e8-9857-a47382456e92.png)

**Comment by mschild** [comment]
![grafik](https://user-images.githubusercontent.com/13733275/42721745-529740e2-8740-11e8-9ea3-3cd6b34f1b82.png)
![grafik](https://user-images.githubusercontent.com/13733275/42721752-6e13d326-8740-11e8-8cc7-4d00f135a0a7.png)

I prefer the first one, what do you think?

**Comment by alexanderpanchenko** [comment]
Sorry - I wanted to say 'reset button on the right side of the compare
button'. This way you can't by accident reset results instead of asking to
results. Also a fair gap between buttons is needed to avoid such false
clicks.
