### ISSUE TITLE
classifier is inconsistent

### ISSUE THREAD

**Issue by mschild** [uhh-lt/cam#81]
![grafik](https://user-images.githubusercontent.com/13733275/42754841-5844c110-88f6-11e8-9ff4-dd4b1bbcc2cc.png)

venus has lower mass than earth - Venus is BETTER
earth has more mass than venus. - Earth is BETTER

**Comment by alexanderpanchenko** [comment]
looks good - pls deploy it.

**Comment by mschild** [comment]
deployed now

**Comment by mschild** [comment]
I introduced a heuristic to check for negations and place the found sentences on the correct side. The result looks quite promising:
![grafik](https://user-images.githubusercontent.com/13733275/43084791-a75c658e-8e99-11e8-9766-41906f3133de.png)
The system with that changes is deployed on http://ltdemos.informatik.uni-hamburg.de/cam2/#/

I also created a testing script which feeds the triples of the prestudy to the backend and calculates precision, recall, f1 and accuracy, based on the scores for the aspects. On that measurements the system with the heuristic also won against the system without: https://docs.google.com/spreadsheets/d/1JkoBS64_pX6APanHgGadkv6FhlSiTh4rR2XnneVcrpI/edit#gid=491163298

**Comment by alexanderpanchenko** [comment]
Thanks - please also give some examples to make sure I got it correctly.

**Comment by mschild** [comment]
@alexanderpanchenko I would like to integrate the heuristic feature in the final Study version of CAM, what do you think? I evaluated it on basis of the comparisons of the prestudy and the aspect dependend scores and it shows a benefit against the system without any heuristic

**Comment by alexanderpanchenko** [comment]
could you please refer to the comparison scores once again? what are the numbers?

**Comment by mschild** [comment]
https://docs.google.com/spreadsheets/d/1JkoBS64_pX6APanHgGadkv6FhlSiTh4rR2XnneVcrpI/edit?usp=sharing

On the left there is the system without any heuristics and the other column with marked fields is the heuristic I would merge into the system.
Actually the mean deviation from the gold score decreased by 2% (0.38 to 0.36) and one comparison less was classified incorrectly (12 instead of 13), according to the score borders I set.

**Comment by alexanderpanchenko** [comment]
Please merge into the system the heuristic, but keep an option to turn it off. Let’s keep it for now, but we need to discuss it during the next 1:1 a bit more closely.

**Comment by mschild** [comment]
I will make another entry in the config for that (besides the index selected). Since it probably won't make sense to give this option to the user.

**Comment by alexanderpanchenko** [comment]
Sure, just at the system startup time.
