### ISSUE TITLE
integrate link to the source document 

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#82]
The new index (depcc*) contains field 'document_id' which contains an URI of the source document. 

<img width="1280" alt="screen shot 2018-07-21 at 9 53 16 pm" src="https://user-images.githubusercontent.com/1456830/43039170-7e35a914-8d30-11e8-9d55-6fa90ebb7348.png">

A hyperlink to the source document should be added in the interface so that a user can go to the original document and see the sentence with a comparison in a context. This element of the UI is expected to ensure the trust of the users - sentences are not coming from some random source, but rather can be observed in a context.

**Comment by alexanderpanchenko** [comment]
http://ltdemos.informatik.uni-hamburg.de/depcc/app/kibana#/discover?_g=()&_a=(columns:!(document_id,text),index:'5348ece0-3bf3-11e8-92c7-fb1018bda9ba',interval:auto,query:(language:lucene,query:'python%20vs%20matlab'),sort:!(_score,desc))

**Comment by mschild** [comment]
Although there are more sentences included in the new depcc index there are found less hits for the triples (if you only search in the text field: text:() ) what is the difference between the both indexes?

**Comment by mschild** [comment]
And how do I access the new index? Since when I use http://ltdemos.informatik.uni-hamburg.de/depcc-index/depcc/_search?q=text:watermelon%20AND%20apple%20AND%20sugar instead of http://ltdemos.informatik.uni-hamburg.de/depcc-index/commoncrawl2/_search?q=text:watermelon%20AND%20apple%20AND%20sugar there are found 56 hits whereas in Kibana there are 46 hits with depcc and 113 hits with commoncrawl

**Comment by alexanderpanchenko** [comment]
Hello, 

Yes, this is normal. The new index is still in preparation (new documents are being added). The main difference of the old / new indices are:

- new contains duplicates
- new contains 15 billion sentences (will contain) the old contain 3 billion sentences
- new contains URIs

Because the index is still in preparation, I suggest to make the index backend configurable so that both indices can be used (but if URI is available then links to the source documents are shown). It makes sense in my opinion currently to keep at /cam the current version, but deploy the system based on the ‘depcc’ new index to /cam2 or /cam3 to discuss concretely how to implement in the UI the links.

**Comment by mschild** [comment]
Alright, thanks for the update of the depcc index. 
What is the reason for not filtering the duplicates on that index?

I introduced two versions of presenting the corresponding source:
1. A button is shown behind every sentence, which displays the source on hover and opens a new tab (loading that url) on click.
2. The sentence itself is clickable and displays the source on hover. When the sentence is clicked the source is loaded in a new tab.

The version is deployed here: http://ltdemos.informatik.uni-hamburg.de/cam3/#/ the sentences on the left follow the first and the sentences on the right the second approach.
As far as we don't need to mark something on the sentences I would prefer the second approach.

**Comment by alexanderpanchenko** [comment]
> On Jul 23, 2018, at 4:56 PM, Matthias Schildwächter <notifications@github.com> wrote:
> 
> Alright, thanks for the update of the depcc index.
> What is the reason for not filtering the duplicates on that index?
> 
> 
just because sources may be different. 
> I introduced two versions of presenting the corresponding source:
> 
> A button is shown behind every sentence, which displays the source on hover and opens a new tab (loading that url) on click.
ok. thanks - i will check it out.

**Comment by alexanderpanchenko** [comment]
i looked at both versions. both are actually quite nice - great job!

i think for now let’s keep the version on the right (with the underlines). it is also a bit less transparent wrt type of the index - if no URI is available underline is just not shown (but nothing is changed visually)

**Comment by alexanderpanchenko** [comment]
> On Jul 23, 2018, at 5:24 PM, Matthias Schildwächter <notifications@github.com> wrote:
> 
> Yes, good point with the transparency indeed.
> I will update the version to fully use the presentation on the right.
> 
> 
ok

> What did you mean by making the system configurable for both indexes?
> Like a slider which selects depcc/commoncrawl2 (like for fast search)?
> 
no, just on the startup in a conf file

**Comment by mschild** [comment]
Deployed it again.

Ok I will have a look how to use a config file in python.

**Comment by alexanderpanchenko** [comment]
just use a json to store most important configs (or YAML)

**Comment by mschild** [comment]
I would like to merge this branch into master and close this issue if you don't have any concerns left.

**Comment by alexanderpanchenko** [comment]
Okay
