### ISSUE TITLE
Integrated interface for the match in context

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#83]
I suggest thinking if we can further improve #82 by integrating the text of the document directly in the application (instead of a direct hyeprlink which should remain but probably be the second source of context): 

The new index allow us reconstruction of the document (if sorted by ``sentence_id``):

![image](https://user-images.githubusercontent.com/1456830/43368726-2926a7ce-9362-11e8-8192-ea41c62b95e6.png)

Therefore, we can design a pop-up where the user can observe the sentence in context (highlighted, which is not possible with the external links!).

**Comment by mschild** [comment]
I thought about something similar:
When the link is clicked a search for the corresponding sentence is automatically triggert on the opened website.
But I don't really now if that is possible to achieve (as you stated).

Your idea also has the advantage, that the user can stay on the application and there is probably no need to leave it for the source. In addition, it is possible to just show the nearest context for the sentence (not the whole document but maybe the 2-3 sentences bevore and after the highlighted one) to speed up the determination process -> paragraph instead of document size.

**Comment by alexanderpanchenko** [comment]
> On Jul 30, 2018, at 9:46 AM, Matthias Schildwächter <notifications@github.com> wrote:
> 
> I thought about something similar:
> When the link is clicked a search for the corresponding sentence is automatically triggert on the opened website.
> But I don't really now if that is possible to achieve (as you stated).
> 
> 
I think it is not possible in general for all browsers and platforms.

Your idea also has the advantage, that the user can stay on the application and there is probably no need to leave it for the source. In addition, it is possible to just show the nearest context for the sentence (not the whole document but maybe the 2-3 sentences bevore and after the highlighted one) to speed up the determination process -> paragraph instead of document size.

Yes, exactly. Focusing on the closest context makes much more sense than opening a new page (a sentence can be somewhere in the bottom left corner).

**Comment by mschild** [comment]
The first example of this feature:
![grafik](https://user-images.githubusercontent.com/13733275/43592936-e8fc86ce-9676-11e8-9823-9e2805d134c2.png)
![grafik](https://user-images.githubusercontent.com/13733275/43592969-00b5d45a-9677-11e8-982e-b486274c98b8.png)
Maybe it is also useful to make the context range adaptable by the user. 
When everything is marked just like in the presented sentences, it looks a bit messy, maybe this clean solution fits better.

**Comment by alexanderpanchenko** [comment]
nice, but i would keep the color scheme exactly as in the link (with the ‘Venus’, ‘mass’, and ‘Earth’ being colored in the same way, while you can still highlight the entire sentence but not so aggressively).

**Comment by alexanderpanchenko** [comment]
Much nicer. A couple of hints:

- Put the yellow sentence highlighting in the background and make it a big brighter. 

- Add a possibility to see entire document without clicking the link (e.g. by clicking on the […] symbols)

**Comment by alexanderpanchenko** [comment]
I agree - highlighting should be done only in the sentence, not in the entire text (it distracts in my opinion the user)

**Comment by mschild** [comment]
![grafik](https://user-images.githubusercontent.com/13733275/43636372-2ddceb1c-9712-11e8-86b0-41f42d5b481c.png)
The document size querying is a bit buggy at the moment, as soon as i fixed it, I will deploy it on cam3

**Comment by alexanderpanchenko** [comment]
oh, nice. I would rather include a button ‘show full document’ or something (giving to much knobs to the user is not a good idea IMO)

**Comment by alexanderpanchenko** [comment]
I like the overall visual highlighting of the sentence now - let’s keep this version.

**Comment by mschild** [comment]
Then also at least two buttons are needed one to show the document and one to return to the smaller view, I would like to deploy that version and let you have a look, to discuss the advantages/disadvantages.

**Comment by mschild** [comment]
I deployed it on http://ltdemos.informatik.uni-hamburg.de/cam3/#/ now, so you can have a look if you have time.

The contexts:
- Short: 1 sentence before and after
- Medium: 3 sentences before and after
- Document (maybe rename to "All"): shows everything stored with the document_id

**Comment by alexanderpanchenko** [comment]
I would go for medium as the default choice and leave out the short one. 

Mind the formatting issues for long urls here - the window should be made wider. 

For the document, I would just call this button ‘show all’:

**Comment by mschild** [comment]
![grafik](https://user-images.githubusercontent.com/13733275/43656546-1621a670-9753-11e8-89b8-7c264f684dcc.png)

I changed the width from 30% to 40%, probably most of the urls will now fit without breaking.
(or do you have an example where the formatting breaks?)
I dismissed the Short button and renamed Medium to "Show Near", probably you are right and the short context doesn't hold a great benefit.

**Comment by alexanderpanchenko** [comment]
looks good.

**Comment by alexanderpanchenko** [comment]
i think even 50% would be fine

**Comment by mschild** [comment]
Now merged into master (for the moment still accessible on http://ltdemos.informatik.uni-hamburg.de/cam3/#/ ). It only is used if the config of the system is set to the depcc index.
