### ISSUE TITLE
remove duplicate sentences from the output

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#85]
![image](https://user-images.githubusercontent.com/1456830/43841662-f719adca-9b23-11e8-8ecc-4f1d216aa8a2.png)

**Comment by mschild** [comment]
Should duplicates with different document_ids also be removed?
There are still a lot:
On http://ltdemos.informatik.uni-hamburg.de/cam3/#/ for the triple (aac, mp3, sound quality) e.g. there is seven times the same sentence, but with different document ids (see the picture).

Probably, it is best to just keep one of these and if another duplicate with the same document_id appears the system takes the one with the lower sentence_id

![grafik](https://user-images.githubusercontent.com/13733275/44152598-3e091d1a-a0a6-11e8-99b7-f94b23462ddd.png)

**Comment by alexanderpanchenko** [comment]
how different are the documents? 

i agree with you

**Comment by mschild** [comment]
Totally different acutally:
http://www.top4download.com/free-mp3-player/
http://mp3-to-wave-converter.winsite.com/freeware/
http://www.winsite.com/convert/convert+mp3+to+wave/freeware/
https://www.scribd.com/doc/46457203/Audio-Compression-Standards
http://www.easyfreeware.com/freeware/mp3_to_wave_converter.html
http://www.filebuzz.com/fileinfo/102816/MP3_to_AAC_Converter.html
http://shareme.com/programs/amd/athlon-xp-m-1900-audio-driver

**Comment by alexanderpanchenko** [comment]
then it is not a bug, but a feature :-) 

maybe in these cases, we just want to group all URLs and show to the user all of them - it may be actually quite strong extra information that confirms that this fact is correct. something like a pop-up choice of the url for those documents (instead of a direct link) could be a solution without the lost of the information.

**Comment by mschild** [comment]
Yes, thats true, some kind of grouping would be nice.
Probably the number of urls per sentence should also rank a sentence higher.

Implementing this feature could be time constraining, but I will see.

**Comment by alexanderpanchenko** [comment]
OK.

**Comment by mschild** [comment]
To stay at the example above, with the aggregation it now looks like this:
![grafik](https://user-images.githubusercontent.com/13733275/44269111-dd9ebe00-a233-11e8-8a6f-045e66eadf36.png)
Furthermore, it is now possible to select the url to show the corresponding context on sentences with more than one document_id:

# Option one:
![grafik](https://user-images.githubusercontent.com/13733275/44269161-06bf4e80-a234-11e8-8b85-ec25fda39478.png)
The button on the right of the dropdown is there to open the link in another tab.

# Option two:
![grafik](https://user-images.githubusercontent.com/13733275/44271426-615ba900-a23a-11e8-89be-3ff7d107010d.png)
When the Link-button is clicked the following window is shown:
![grafik](https://user-images.githubusercontent.com/13733275/44271487-8f40ed80-a23a-11e8-9b5d-c2b5287e02f8.png)

**Comment by mschild** [comment]
Alright, I deployed both versions:
To see aggregation you could try: aac vs. mp3 wrt. sound quality as above.
Option one:
http://ltdemos.informatik.uni-hamburg.de/cam3/#/

Option two:
http://ltdemos.informatik.uni-hamburg.de/cam2/#/

I am not really sure what is better, option one is more compact and directly shows the context. Option two in contrast has a better overview of the document ids.

**Comment by alexanderpanchenko** [comment]
I like better the cam3 - it let you more easily go back and forth b/w different options

**Comment by alexanderpanchenko** [comment]
wrong font (times) is here for ‘sound quality'

**Comment by mschild** [comment]
Ok, thats true, and basically you also have the overview when you click on the dropdown. Tomorrow, I will merge this feature into master to finalize the study setup.

I don't get what you mean by: _wrong font (times) is here for ‘sound quality'_ can you explain a little bit?

**Comment by alexanderpanchenko** [comment]
> On 17 Aug 2018, at 20:07, Matthias Schildwächter <notifications@github.com> wrote:
> 
> Ok, thats true, and basically you also have the overview when you click on the dropdown. Tomorrow, I will merge this feature into master to finalize the study setup.
> 
> 
ok - great 
> I don't get what you mean by: wrong font (times) is here for ‘sound quality' can you explain a little bit?
> 
> —
> 

sorry - i mean that there should be no ‘Times New Roman’ or similar fonts normally.

**Comment by mschild** [comment]
The labels for the score charts have different fonts, right? That again is a mac specific bug, I am testing on Firefox and Chrome and both use the same fonts as for example in the sentences.

**Comment by alexanderpanchenko** [comment]
I think it was on chrome

**Comment by mschild** [comment]
The fonts should be the same now (solved by 24e4d2c37d3a244872ea8088a83d88352be0e18a)
