### ISSUE TITLE
try to generate candidates for comparison 

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#86]
Given a word, like 'python' generate the list of candidate, like in Google 'python vs ...' .

1. Get all sentences containing the target words (python)

2. Classify them (first word = python, second word = last / first noun in the sentence, text = input sentence).  OR Classify them iterating over all nouns in the sentence (first word = python, second word = i-th noun in the sentence, text = input sentence). 

3. Rank the nouns found in the sentences by the total number of comparative sentences (with a high threshold). No normalization is needed - just take the raw sentence counts.

**Comment by alexanderpanchenko** [comment]
Caching mechanism is important not to re-compute everything from scratch every time.

**Comment by mschild** [comment]
I now tried a different approach:
1. I query sentences containing with the following query: "_text:(\<object\> AND vs)_" where \<object\> is "python" for example
2. I take the nouns (NN) where the following pattern matches: (<object> (vs|vs.) candidate | candidate (vs|vs.) <object>)
Alone this two steps deliver quite good results for comparison candidates (for python):
[('perl', 22), ('java', 15), ('php', 13), ('ruby', 9), ('alligator', 7), ('c', 6), ('lua', 4), ('r', 3), ('julia', 2), ('c++', 2), ('haskell', 2), ('crocodile', 1), ('tiger', 1), ('cat', 1), ('deer', 1), ('kruger', 1), ('gator', 1), ('qml', 1), ('ptrace', 1), ('jlizard', 1), ('visual', 1), ('dog', 1), ('kc', 1), ('scheme', 1), ('javascript', 1)]

3. I still need to filter out some candidates like "kruger" do you think common hypernyms (wordnet) could be helpfull for this? Are there standard functions to get common hypernyms for **words** I only found one for synsets...

Another approach could be to query the sentences belonging to the object and a candidate and count the sentences classified as "BETTER" or "WORSE", but that is very costly.

What do you think about the first 2 steps?

**Comment by mschild** [comment]
Wordnet seems not te be useful for the python example after filtering out all candidates, not containing a common hypernym to **python** only these are left:

[('java', 13), ('alligator', 4), ('ruby', 4), ('scheme', 1), ('crocodile', 1), ('tiger', 1), ('cat', 1), ('gator', 1), ('kc', 1), ('deer', 1)]

For many candidates there were no hypernym at all (e.g. perl, lua, c++) as can also be viewed here: http://wordnetweb.princeton.edu/perl/webwn

**Comment by alexanderpanchenko** [comment]
I would expect that WordNet is not useful - it coverage is quite limited. 

However, distributional models can be useful. 

Here you will find the word similarities (AKA distributional thesaurus JoBimText) computed exactly from our corpus. 

http://ltdata1.informatik.uni-hamburg.de/depcc/distributional-models/dependency_lemz-true_cooc-false_mxln-110_semf-true_sign-LMI_wpf-1000_fpw-1000_minw-5_minf-5_minwf-2_minsign-0.0_nnn-200/SimPruned/ <http://ltdata1.informatik.uni-hamburg.de/depcc/distributional-models/dependency_lemz-true_cooc-false_mxln-110_semf-true_sign-LMI_wpf-1000_fpw-1000_minw-5_minf-5_minwf-2_minsign-0.0_nnn-200/SimPruned/>

You can try to use them to generate more candidates.

**Comment by mschild** [comment]
For the second filter approach the following comparison candidates were selected:
['lisp', 'lua', 'scheme', 'perl', 'visual', 'jython', 'net', 'cython', 'ruby', 'java', 'javascript', 'php', 'node', 'boa', 'julia', 'alligator', 'qml', 'python programs', 'cat', 'deer', 'crocodile', 'octave', 'tiger', 'arc', 'sas', 'gator', 'aqueon', 'prothon', 'ruby ruby', 'stones', 'brython', 'ruby performance', 'gql', 'nspr', 'pycuda']

They are sorted by found comparative sentences for python and the candidate. If only candidates with more than 40 comparative sentences are shown, probably the best get presented:
['lisp', 'lua', 'scheme', 'perl', 'visual', 'jython', 'net', 'cython', 'ruby', 'java', 'javascript', 'php', 'node', 'boa', 'julia']

comparing with google:
![grafik](https://user-images.githubusercontent.com/13733275/47662339-02e86a80-db9b-11e8-84fe-3e43cc7e8222.png)

Only _r_, _c++_, _matlab_ and _go_ are not found so 60% are found and in addition there are found some more, which could also be interesting.

**Comment by alexanderpanchenko** [comment]
I find this approach very interesting. Would be really great to show more examples of these… 

Use the DT JoBimText to filter in step 3 (see my other mail for details).

**Comment by alexanderpanchenko** [comment]
looks quite good. actually i think that it is already worth deploying it (to see how it works more realistically and to be able to play with it…)

**Comment by alexanderpanchenko** [comment]
> On Oct 29, 2018, at 5:29 PM, Matthias Schildwächter <notifications@github.com> wrote:
> 
> Thanks for the hint with JoBim text, I hope it is easy to get, how to use it.
> 
> 
the all files are big, but you can trim them considerably by sorting all the values by the scores and keeping some 20% of top entries and removing the remaining 80% of the word pairs.
> About deploying, at the moment it is not realy operating in real time, it takes about 15 seconds to process step 1 and 2. The filtering (step 3) using the BoW classifier features set takes minutes.
> 
ok. maybe later then

**Comment by alexanderpanchenko** [comment]
No, in your case just download the files I gave the link to (a bunch of archives). You will get a huge set of triples word1:word2:similarity. I would index them using elastic search and use at stage 3. Th JoBimText model includes much-much more parts you do not need. This is the part called DT.

**Comment by mschild** [comment]
Alright, thank you very much for the clarification, I though I have to understand how to set up and use JoBimText now.
I will have a look how good that works for filtering the candidates, thanks!
