### ISSUE TITLE
Improve extracting aspects using "because" sentences

### ISSUE THREAD

**Issue by ChulioZ** [uhh-lt/cam#88]

**Comment by ChulioZ** [comment]
@alexanderpanchenko 

Here's my status report for the last two weeks:

I have begun to extract aspects using only sentences with a "because" in it. I have tried various other options ("reason", "as") but those have to be tested further within the next weeks.

For now, I'm extracting aspects from the because-sentences in the following way:

- I use only nouns and those adjectives and adverbs that are comparative (easier for example).
- I currently only extract one aspect per sentence per POS tag, so currently a maximum of three aspects per sentence (one noun, one comparative adjective and one comparative adverb).
- I currently extract the word that fulfills the following features: it has the right POS tag, it's closest to but after "because", it's not contained in a list of "stopwords" (I exclude words that shouldn't make much sense such as "less", "way", "people", "things", "lol", "idiot").

You can see the results for CAM's example comparisons in [this Google spreadsheet](https://docs.google.com/spreadsheets/d/1RPpmP3hf9oxVe44nop1XbFibRgiAobBH0rz3qAjALy4/edit?usp=sharing).

For further clarification: Columns 1 and 2 are, quite obviously, the objects to compare. Columns 5 and 6 are all the aspects I extract using the method I described above. Columns 3 and 4 however are the "best" of those aspects -- they are ranked via the TF-IDF method so that aspects that are common for one object but rare for the other are those that are the most important for this object.

As you can see, the numbers are quite low. For many comparisons, such as potato vs. steak, I haven't found a single aspect for either object using this method. Even for the comparisons that have a lot of results and even a lot of aspects found, such as apple vs. microsoft, there are not a lot of aspects that appear more than once (in the apple example, only the five best aspects have a number greater than 1). As my next goal I will definitely try to raise these numbers. Things I'll test in the near future will include:

- Using other "trigger words" instead of just "because" ("reason", "as" are two I have already tried for example, but not as thoroughly as "because")
- Extracting more than one aspect per POS tag per sentence (that would make sense for sentences such as "... is better than ... because of this and that and this and that" but of course there are also sentences where this doesn't make any sense at all)
- Extracting aspects that are in front of the "because" (won't make that much sense for just the because sentences but will make sense for "reason" for example)

All this being said, I still like the first results I have. I think the aspects I've extracted in the examples, even if their amount is a little bit too small, may be the best fitting aspects we've yet seen for these comparisons. Many of them actually belong to the comparison and not to the object itself and many of them actually make sense. Of course there are still aspects that don't belong there but in my opinion the overall quality is higher than before.

For the next weeks, expect my weekly reports mostly on the weekends as my weekdays are pretty full.

**Comment by alexanderpanchenko** [comment]
@ChulioZ 

Thanks for the report. It would be great if you continue with the reports of the same level of details. It is very helpful. I have a few comments: 

Overall, I agree that the results look nice, but are sparse. To deal with this issue, I suggest to : 

- use more constructions than just 'because' (collect more similar keywords)

- union most frequent aspects of both words. The use-case is to propose to the user some useful aspects that will distinguish one object from another. 

> I currently only extract one aspect per sentence per POS tag, so currently a maximum of three aspects per sentence (one noun, one comparative adjective and one comparative adverb)."

Can you elaborate more on this? What is the motivation? Please give an example. 

> Extracting more than one aspect per POS tag per sentence (that would make sense for sentences such as "... is better than ... because of this and that and this and that" but of course there are also sentences where this doesn't make any sense at all)

Probably this is what you mean here - extract more aspects. 

> Extracting aspects that are in front of the "because" (won't make that much sense for just the because sentences but will make sense for "reason" for example)

Yes, probably this won't make much sense.

**Comment by ChulioZ** [comment]
@alexanderpanchenko 
Here's my report for this week.

First of all, answers to your questions:

> use more constructions than just 'because' (collect more similar keywords)
I've done that but I'm not yet satisfied with the results. More on that will follow.

> union most frequent aspects of both words. The use-case is to propose to the user some useful aspects that will distinguish one object from another.
I haven't really unioned them but my ranking algorithm now divides the amount of how often an aspect is found for one object by the amount of how often the aspect is found for the other object. For example, if we have Python and Matlab and both of them have the aspect "speed" but Python has it 5 times and Matlab only once, Python's value for speed will stay at 5 and Matlab's value for speed will decrese to 0.2 which won't be enough to keep it in the top list of aspects found.

> try to look at the example sentences yourself
I've done that and I'm still in the process of doing that to further improve the results. Conclusions I've drawn from this will follow later in this report.

> Can you elaborate more on this? What is the motivation? Please give an example.
My thinking was that usually a sentence could look like "A is better than B because of thing" or "Because of this X is better than Y". Sentences could also look like "A is better than B because of thing and that's why I've bought a computer with totallyanotherthing" and in this case I wouldn't want computer and totallyanotherthing in my extracted aspects. On the other hand, if we have a sentence like "A is better than B because of thing and anotherthing and also thisone", we absolutely want anotherthing and thisone in our aspects. I'm still trying to find the best algorithm for this.

I have tried various ways to improve on the results. Not all the possibilites I've tried were successful, but I've got some good ideas on how to continue improving the extracted aspects in the near future.

Things I've done this week include:

- I've added 5 additional sheets to the spreadsheet I've posted last week. Those show 6 (including the one from last week which was also reworked) different ways of extracting aspects. The method used to get each sheet is described in its header.

- I've tried additional trigger words like because: since, reason, for, as. Results using these words can be found in sheets 2 and 4. This method drastically increases the number of aspects found but in the examples it looks like the quality is definitely decreased. For example, in Python vs. Java we now find aspects like programmers or c++ which are bad aspects. On the other hand, we now find JIT for example which could be a good aspect.

- I've tried collecting not only one aspect per sentence (for example, the first noun I find after because) but all possible aspects instead (all nouns after because). Results using this method can be found in sheets 3 and 4. This method also increases the number of aspects found and it also doesn't seem to decrease the quality of aspects, at least not much. This seems to be the way to go for further tests.

- Because of the drastic reduction in quality when choosing more trigger words than just because I've looked into the sentences containing specifically for and as. As you can imagine, most for's and as's in a sentence aren't there for justifying anything but are just "normal" sentence elements. "I like A more than B for it is cooler" would be a sentence we want, but sentences like "A is better than B so I bought it for my mum" are more common. We can't really use for and as this way. Instead I've found a better way to use them: Many sentences were of the following structure: "A is better for doing X than B". This is actually a very good sentence to extract an aspect - "doing X". So I've removed for and as as trigger words again and instead I've looked for these exact situations. Results from this method can be found in sheets 5 and 6. I like these results a lot qualitywise but they are still pretty sparse, although way less so than if we only use because and nothing else. A goal for next week is to further look into these structures and see if I can improve my way of finding them.

- The other two words I've tested, since and reason, are completely removed again for this last method. That's because I haven't been able to further look into the structures of sentences that contain these words and qualify for our needs. That's one of my goals for next week.

- Another goal for next week is to find even more words like because that could also lead to useful sentences.

- I've also noted that words like "slower" were extracted as aspects which doesn't really make sense. I mean, structure-wise it makes perfect sense: "A is slower than B" is a sentence CAM includes (and should include) and speed is a relevant aspect, so we do want to find it - just not in this form. As B wins this sentence B will also get the extracted aspect so in the end we can see B's aspect of winning is slower ... That doesn't make much sense. To prevent this I've mapped negative words like that to their positive counterpart, so in this example B would actually get "faster" as an extracted aspect for this sentence.

That's all I have for this week. I'm looking forward to improving my results within the following weeks, trying out the other ideas I have!

Any questions, comments, ideas?

**Comment by ChulioZ** [comment]
@alexanderpanchenko 
As I have a lot of things to do this weekend I won't write a report this week but instead write a bigger one next weekend. I hope that's okay.

**Comment by ChulioZ** [comment]
@alexanderpanchenko 

Here's my report for this week and the last.

I added another sheet to [my Google spreadsheet](https://docs.google.com/spreadsheets/d/1RPpmP3hf9oxVe44nop1XbFibRgiAobBH0rz3qAjALy4/edit#gid=997690493) with the newest results in my search for the best aspect finding method. I'm actually quite satisfied with my improvements.

Let me first explain how these new results are calculated:

- I now use three "trigger words": 1. "because", 2. "as PRONOUN VERB", 3. "since PRONOUN VERB", 4. "for PRONOUN VERB". The first one is self-explanatory. For numbers 2-4, VERB means that there has to be any kind of verb after "as it" or "since it" or "for it" for the sentence to be triggered and PRONOUN means that there has to be a pronoun in between. For example: "A is better than B since it is better for typing" would be a triggered sentence; "A is better than B for my dog" wouldn't. Allowing any kind of verb means I'll find sentences with "as it is", "for they allow", "since we can" and many more.

- When a sentence is triggered, all nouns that appear after the trigger word are collected as aspects for the winning object of the sentence.

- In addition to that, all comparative words are collected as aspects for the winning object of the sentence. For example, "easier" or "faster". I exclude words such as "better" or "more" because they have no real information for our aspects (knowing an object is better doesn't reveal why it's better which is what the aspects are supposed to tell. Faster on the other hand reveals a lot more).

- In addition to that, all comparative words that are followed by a specific structure are collected. That is, if the comparative word is followed by "for" or "to". In these cases, not only the word itself is collected as an aspect but the following words as well (until some kind of "stopper"). Examples: "A is better for spotting enemies, I like it more than B" would result in the aspect "better for spotting enemies". This is supposed to diversify the aspects and give additional information.

- When ranking the aspects, the following calculation is used: For each aspect, I count how often it occurs for the first object and for the second object, then its score for each object is the quotient of that object's count of that aspect divided by the other object's count of that aspect. Example: Python has 11 occurences of "easier", Java has 2. Python thus gets a score of 11/2 for "easier", Java gets 2/11. The object that has the lower score then loses this aspect entirely so that aspects are unique among both objects. If both objects have the same score, they both lose the aspect (it doesn't seem to help distinguish the objects).

If I haven't forgotten anything, that's basically the process behind the current results. I do think that the results are quite a bit better than those from the previous weeks; both in quality and in quantity.

In addition to improving on the results I've also made a lot of improvements on the code structure via refactorings, code formattings etc. to prepare for implementing and committing the new methods within the "real" CAM code.

There are a few more things I have on my TODO list for next week:

- Collect aspects that are between the marker and "than", for example: "A has better speed than B" should result in the aspect "speed" even if there's no trigger word such as because here. I'll have to further analyze how structures like that normally appear in the sentences to find out the best way of finding them. Also I'll have to make sure that I'm not collecting aspects more than once, for example "A is better for typing than B" shouldn't result in typing being found by this method and also by the "better for" method I described above.

- Write comments to prepare for implementing and committing the new methods within the "real" CAM code.

**Comment by alexanderpanchenko** [comment]
Thank you for the detailed report and the updates. I agree that the results
look indeed much better now. Please integrate the new approach now in the
production system and deploy them. I think we can advance when we will see
it how it works.

Once this is done a Skype call will be needed to discuss the next step.

**Comment by ChulioZ** [comment]
@alexanderpanchenko 

Integrated and deployed. It's up and running and can be checked on [ltdemos](http://ltdemos.informatik.uni-hamburg.de/cam/).

I'll write you a mail regarding our Skype call. I'll close this issue for now after the deployment until further improvements are requested.
