### ISSUE TITLE
Store the queries of the user in the log of cam-study

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#89]

**Comment by mschild** [comment]
Re-deployed the study system just now. 
Changes included:
- participant number only gets increased, if the user continues after the instructions (hoply to get rid of the jumps in participant numbers)
- the study can now be left by a user after he finished an even number of comparisons, but at least two.
- the bug were "NaN" was shown for the times measured in keyword search is fixed
- the queries of the users are logged now
