### ISSUE TITLE
general comparison

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#90]
I was not sure how 'general comparison' is different from the main bar python/matlab?

![image](https://user-images.githubusercontent.com/1456830/45427783-06ce3500-b6a0-11e8-8468-43eb6e71afe1.png)

**Comment by mschild** [comment]
"Genera Comparison" are all the sentences not containing the the entered aspect(s), whereas the main bar the total score represents. The total score contains all sentences, so basically the bars underneath combined

**Comment by alexanderpanchenko** [comment]
in this case, it should be renamed to like ‘other aspects’ or something of this kind (general comparison is what i would call the ‘overall outcomme’ bar)
