### ISSUE TITLE
Integrate the keyword search function from the study-cam to the production system

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#91]
I think that the original keyword search from the study-cam system can be a useful complementary tool for the CAM system. After all, we want the user to be able to answer the question as quickly as possible and in some scenarios, the keyword search may be just fine (and we do not the user to leave our application). 

I suggest adding an extra tab with the exact same keyword search functionalities as available in the cam-study to the system. 

![image](https://user-images.githubusercontent.com/1456830/45817776-11ac4980-bce0-11e8-87c7-190c982dc585.png)

**Comment by alexanderpanchenko** [comment]
Create a special path like ``/cam/search`` to access this function (and ``/cam/vs/`` for the usual functionality.

**Comment by mschild** [comment]
Please check out this link: http://ltdemos.informatik.uni-hamburg.de/cam2/#/Search

**Comment by mschild** [comment]
I addressed all of your suggestions now.
http://ltdemos.informatik.uni-hamburg.de/cam2/search

What I thought about the improvements when I was almost finished: We wanted to show the keyword search of the study in the demo because we can't present it in the paper?

**Comment by alexanderpanchenko** [comment]
thanks! looks really nice now. Just one small thing:

when one clicks ‘show all’ the target sentence highlight disappers somehow



> On 11 Oct 2018, at 18:51, Matthias Schildwächter <notifications@github.com> wrote:
> 
> I addressed all of your suggestions now.
> http://ltdemos.informatik.uni-hamburg.de/cam2/search <http://ltdemos.informatik.uni-hamburg.de/cam2/search>
> What I thought about the improvements when I was almost finished: We wanted to show the keyword search of the study in the demo because we can't present it in the paper?
> 
> 
Yes, if I got your questions correctly. This is the reason.

**Comment by alexanderpanchenko** [comment]
ah, ok. i see. then it is allright
