### ISSUE TITLE
Supervised aspect extraction

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#95]
Step 1. Prepare a dataset with the OTE annotations in the CoNLL format. SemEval data:
-------

Paper:
http://www.aclweb.org/anthology/S16-1174

Website:
http://alt.qcri.org/semeval2016/task5/

ABSA dataset:
https://drive.google.com/open?id=1TBkw8M53tqqV6v_7JHQCn6qq5l6CAhEV

CoNLL format:
http://universaldependencies.org/format.html

Step 2. Train a classifier to detect OTE in text
----------

Tagger:
https://github.com/achernodub/bilstm-cnn-crf-tagger

For the beginning just try running example datasets from this repository. Then format the SemEval ABSA dataset in this format and train a model.

**Comment by alexanderpanchenko** [comment]
https://github.com/achernodub/bilstm-cnn-crf-tagger

**Comment by alexanderpanchenko** [comment]
if you need to install with pip: https://github.com/pypa/pip/issues/3610

**Comment by alexanderpanchenko** [comment]
about the tagger and its model:
[_2018_Grammarly_v15_preFinal_05.pdf](https://github.com/uhh-lt/cam/files/2522904/_2018_Grammarly_v15_preFinal_05.pdf)

**Comment by ChulioZ** [comment]
Doesn't seem to fit our project. Closed for now.
