### ISSUE TITLE
Include the video to the About page

### ISSUE THREAD

**Issue by alexanderpanchenko** [uhh-lt/cam#96]
Embed the YouTube video to this page so that people can directly watch use-cases not leaving the web site:

![image](https://user-images.githubusercontent.com/1456830/47255077-6f60bc80-d46b-11e8-8ede-bf8344ab23b1.png)

**Comment by alexanderpanchenko** [comment]
Also please include to the corpus used in CAM https://commoncrawl.s3.amazonaws.com/contrib/depcc/CC-MAIN-2016-07/index.html

and the reference to this paper so that people know what to cite.

**Comment by mschild** [comment]
Added to the demo branch and deployed (http://ltdemos.informatik.uni-hamburg.de/cam/about)
